server:
  port: 9091

spring:
  ldap:
    urls: "ldap://localhost:10389"
    base: dc=example,dc=com
    username: uid=admin,ou=system
    password: secret

ldap:
  config:
    company: inetum
    country: france

logging:
  level:
    org.springframework: INFO